set(_CATKIN_CURRENT_PACKAGE "cv_bridge_kinect2")
set(cv_bridge_kinect2_VERSION "0.0.0")
set(cv_bridge_kinect2_MAINTAINER "zhang <zhang@todo.todo>")
set(cv_bridge_kinect2_PACKAGE_FORMAT "1")
set(cv_bridge_kinect2_BUILD_DEPENDS "cv_bridge" "image_transport" "roscpp" "sensor_msgs" "std_msgs")
set(cv_bridge_kinect2_BUILD_EXPORT_DEPENDS "cv_bridge" "image_transport" "roscpp" "sensor_msgs" "std_msgs")
set(cv_bridge_kinect2_BUILDTOOL_DEPENDS "catkin")
set(cv_bridge_kinect2_BUILDTOOL_EXPORT_DEPENDS )
set(cv_bridge_kinect2_EXEC_DEPENDS "cv_bridge" "image_transport" "roscpp" "sensor_msgs" "std_msgs")
set(cv_bridge_kinect2_RUN_DEPENDS "cv_bridge" "image_transport" "roscpp" "sensor_msgs" "std_msgs")
set(cv_bridge_kinect2_TEST_DEPENDS )
set(cv_bridge_kinect2_DOC_DEPENDS )
set(cv_bridge_kinect2_URL_WEBSITE "")
set(cv_bridge_kinect2_URL_BUGTRACKER "")
set(cv_bridge_kinect2_URL_REPOSITORY "")
set(cv_bridge_kinect2_DEPRECATED "")