set(_CATKIN_CURRENT_PACKAGE "point_cloud_test")
set(point_cloud_test_VERSION "0.0.0")
set(point_cloud_test_MAINTAINER "zhang <zhang@todo.todo>")
set(point_cloud_test_PACKAGE_FORMAT "1")
set(point_cloud_test_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(point_cloud_test_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(point_cloud_test_BUILDTOOL_DEPENDS "catkin")
set(point_cloud_test_BUILDTOOL_EXPORT_DEPENDS )
set(point_cloud_test_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(point_cloud_test_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(point_cloud_test_TEST_DEPENDS )
set(point_cloud_test_DOC_DEPENDS )
set(point_cloud_test_URL_WEBSITE "")
set(point_cloud_test_URL_BUGTRACKER "")
set(point_cloud_test_URL_REPOSITORY "")
set(point_cloud_test_DEPRECATED "")